# -*- coding: utf-8 -*-
"""Customer_sentiments_Phase_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfp6cMyrhqVxcXXlmaFvoH7oR0fZmJ2V
"""

!pip install pandas numpy matplotlib seaborn nltk scikit-learn textblob vaderSentiment

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

plt.style.use('ggplot')
nltk.download('vader_lexicon')




try:
    df = pd.read_csv('/content/Reviews.csv')
    print("✅ File loaded successfully.")
except FileNotFoundError:
    print("❌ ERROR: Could not find 'Reviews.csv' in /content. Please check the file name.")

print(f"Original Shape: {df.shape}")
df = df.head(500)
print(f"Working Shape: {df.shape}")

sia = SentimentIntensityAnalyzer()
res = {}



print("Running Sentiment Analysis...")
for i, row in tqdm(df.iterrows(), total=len(df)):
    text = row['Text']
    myid = row['Id']
    res[myid] = sia.polarity_scores(text)

vaders = pd.DataFrame(res).T
vaders = vaders.reset_index().rename(columns={'index': 'Id'})
vaders = vaders.merge(df, how='left')

fig, axs = plt.subplots(1, 3, figsize=(15, 5))
sns.barplot(data=vaders, x='Score', y='pos', ax=axs[0], color='green')
sns.barplot(data=vaders, x='Score', y='neu', ax=axs[1], color='gray')
sns.barplot(data=vaders, x='Score', y='neg', ax=axs[2], color='red')

axs[0].set_title('Positive Sentiment')
axs[1].set_title('Neutral Sentiment')
axs[2].set_title('Negative Sentiment')
plt.tight_layout()
plt.savefig('vader_sentiment_high_res.png', dpi=300, bbox_inches='tight')
plt.show()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction import text




my_stop_words = list(text.ENGLISH_STOP_WORDS) + ['br', 'href', 'quot', 'com', 'http', 'www', 've', 'don']

print("Processing text...")
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words=my_stop_words)
dtm = cv.fit_transform(df['Text'].astype(str))

print("Building Topic Model... (Machine Learning)")
LDA = LatentDirichletAllocation(n_components=5, random_state=42)
LDA.fit(dtm)

topic_results = LDA.transform(dtm)
df['Topic'] = topic_results.argmax(axis=1)

print("\n" + "="*50)
print("="*50)

for index, topic in enumerate(LDA.components_):
    print(f'\nTHEME #{index + 1}')

    top_words = [cv.get_feature_names_out()[i] for i in topic.argsort()[-10:]]
    print(f"Keywords: {top_words}")

plt.figure(figsize=(10,5))
sns.countplot(x='Topic', data=df, palette='viridis')
plt.title('Distribution of Topics Across Reviews')
plt.xlabel('Topic Number (0-4)')
plt.ylabel('Number of Reviews')
plt.savefig('lda_topics_high_res.png', dpi=300, bbox_inches='tight')
plt.show()




print("\n--- Comparative Sentiment Table ---")

comparative_table = vaders.groupby('Score')[['pos', 'neu', 'neg', 'compound']].mean().round(3)
print(comparative_table)




print("\n--- Quantifying False Positives & Negatives ---")

false_positives = vaders[(vaders['Score'] <= 2) & (vaders['compound'] >= 0.05)]
fp_rate = (len(false_positives) / len(vaders[vaders['Score'] <= 2])) * 100

false_negatives = vaders[(vaders['Score'] >= 4) & (vaders['compound'] <= -0.05)]
fn_rate = (len(false_negatives) / len(vaders[vaders['Score'] >= 4])) * 100

print(f"Total 1 & 2 Star Reviews: {len(vaders[vaders['Score'] <= 2])}")
print(f"False Positives (Sarcasm/Mismatch): {len(false_positives)} ({fp_rate:.2f}%)")
print(f"Total 4 & 5 Star Reviews: {len(vaders[vaders['Score'] >= 4])}")
print(f"False Negatives (Hard-Positives): {len(false_negatives)} ({fn_rate:.2f}%)")




plt.figure(figsize=(8, 5))

sns.countplot(data=df, x='Score', palette='viridis')
plt.title('Distribution of Reviews by Star Rating')
plt.xlabel('Star Rating (1-5)')
plt.ylabel('Number of Reviews')
plt.savefig('review_distribution_high_res.png', dpi=300, bbox_inches='tight')
plt.show()